version: 2.1

aliases:
  - &on_master_after_test
    context: shardlabs
    filters:
      branches:
        only:
          - master
    requires:
      - test

jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install development tools
          command: ./scripts/install_dev_tools.sh
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Lint
          command: poetry run pylint starknet_devnet
      - run:
          name: Setup example
          command: ./scripts/setup_example.sh
      - run:
          name: Test CLI
          command: ./scripts/test_cli.sh
      - run:
          name: Test CLI with authentication
          command: ./scripts/test_cli_auth.sh
      - run:
          name: Test plugin - dockerized
          command: ./scripts/test_plugin.sh
          no_output_timeout: 1m
          environment:
            HARDHAT_CONFIG_FILE: ../scripts/hardhat.config.dockerized.ts
            TEST_FILE: test/quick-test.ts
      - run:
          name: Test plugin - venv
          command: ./scripts/test_plugin.sh
          no_output_timeout: 1m
          environment:
            HARDHAT_CONFIG_FILE: ../scripts/hardhat.config.venv.ts
            TEST_FILE: test/sample-test.ts
  package_build_and_publish:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: ./scripts/package_build_and_publish.sh
  image_build_and_push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: ./scripts/image_build_and_push.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - package_build_and_publish:
          <<: *on_master_after_test
      - image_build_and_push:
          <<: *on_master_after_test
