version: 2.1

aliases:
  - &on_master_after_test
    context: shardlabs
    filters:
      branches:
        only:
          - master
    requires:
      - test

jobs:
  test:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install development tools
          command: ./scripts/install_dev_tools.sh
      - run:
          name: Install dependencies
          command: ./scripts/install_dependencies.sh
      - run:
          name: Lint
          command: poetry run pylint starknet_devnet test
      - run:
          name: Setup example
          command: ./scripts/setup_example.sh
      - run:
          name: Test interaction with Starknet CLI
          command: python3 -m test.test_cli
      - run:
          name: Test interaction with Starknet CLI (with authentication)
          command: python3 -m test.test_cli_auth
      - run:
          name: Test endpoints directly
          command: poetry run pytest -s -vv test/test_endpoints.py
      - run:
          name: Test postman
          command: poetry run pytest -s -vv test/test_postman.py
      - run:
          name: Test dumping/loading
          command: poetry run pytest -s -vv test/test_dump.py
      - run:
          name: Test get state update endpoint
          command: poetry run pytest -s -vv test/test_state_update.py
      - run:
          name: Test get transaction trace endpoint
          command: poetry run pytest -s -vv test/test_transaction_trace.py
      - run:
          name: Test plugin - dockerized
          command: ./test/test_plugin.sh
          no_output_timeout: 1m
          environment:
            HARDHAT_CONFIG_FILE: ../test/hardhat.config.dockerized.ts
            TEST_FILE: test/quick-test.ts
      - run:
          name: Test plugin - venv (tests various cases in sample-test)
          command: ./test/test_plugin.sh
          no_output_timeout: 1m
          environment:
            HARDHAT_CONFIG_FILE: ../test/hardhat.config.venv.ts
            TEST_FILE: test/sample-test.ts
  package_build_and_publish:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: ./scripts/package_build_and_publish.sh
  image_build_and_push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: ./scripts/image_build_and_push.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - package_build_and_publish:
          <<: *on_master_after_test
      - image_build_and_push:
          <<: *on_master_after_test
